name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Type check
        run: npm run typecheck --if-present || npm run type-check --if-present || npx tsc --noEmit

      - name: Run unit tests
        run: npm run test --if-present || npx vitest run

      - name: Build extension
        run: npm run build

      - name: Zip dist for Chrome Web Store
        run: cd dist && zip -r ../dist.zip .

      - name: Upload dist.zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-dist
          path: dist.zip
